djangobasico/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('favoritos.urls')),
    path('api-auth/', include('favoritos.urlsrf'))
    
]

favoritos/urls.py
from django.urls import path
from favoritos.views import *


app_name = 'favoritos'

urlpatterns = [
    path('', index_favoritos),
    path('lista', lista_favoritos,name='lista'),
    path('crear',crear_favoritos,name='crear'),
    path('borrar/<int:pk>', borrar_favoritos, name='borrar'),
    #path('borrar/<int:pk>', borrar_favoritos)    #estamos diciendo que "pk" va a ser int, si no se hace esto: lo tomará como string
    path('detalle/<int:pk>',detalle_favoritos, name='detalle'),
    path('actualizar/<int:pk>',actualizar_favorito, name='actualizar')
]

favoritos/models.py
from django.db import models

# Create your models here.

class Favoritos(models.Model):
    nombre = models.CharField(max_length=50, blank=True)
    apellido = models.CharField(max_length=50, blank=True)
    url = models.URLField(max_length=200)
    

favoritos/forms.py
from django import forms
from favoritos.models import Favoritos

class FavoritoForm(forms.Form):           #formulario/// podemos buscar info en "formularios Django"
    nombre = forms.CharField()
    apellido = forms.CharField()
    url = forms.URLField()                 #
    pass

class FavoritoModelForm(forms.ModelForm):      #
    class Meta:
        model = Favoritos
        fields = ["nombre","apellido","url"]
    pass

favoritos/views.py
from django.shortcuts import render, redirect
from .models import Favoritos
from .forms import FavoritoForm, FavoritoModelForm
from django.urls import reverse

# Create your views here.

def index_favoritos(request):
    
    return render(request, 'index.html')


def lista_favoritos(request):
    
    favortos_lista= Favoritos.objects.all()     #estoy viendo en Favoritos (la lista sql) los objetos en la lista
    context = {'favoritos_lista' : favortos_lista }
    
    for fav in favortos_lista:
        print("nombre: " + fav.nombre + "\nApellido: " + fav.apellido + "\nURL: " + fav.url + "\n")


    return render(request, 'favoritos/listas.html', context)

def crear_favoritos(request):
    
    form = FavoritoForm()           #el motor de Django tiene algo llamado contexto. que es lo que podemos mandar desde las VISTA a la plantilla html
                                    #Y este contexto es un diccionario

    if request.method == "POST":
       
        form = FavoritoModelForm(request.POST) #request.POST es datos vinculantes al formulario
        context= {'form':form}
        #nombre=request.POST['nombre']
        #url=request.POST['url']
        

        if form.is_valid():                 #para obtener los datos limpios
            ##cleaned_data{} es donde podremos encontrar todos los datos del formulario validado
            #nombre = form.cleaned_data['nombre']
            #url = form.cleaned_data['url']
            #Favoritos.objects.create(nombre=nombre, url=url)     #ORM transformando de python a sql

            form.save()
        else:
            print(form.errors)
    context= {'form':form , 'titulo' : 'Agregar'}
        # fav = Favoritos()                                
        # fav.nombre = nombre
        # fav.url = url
        # fav.save()      #guardamos, crea el codigo sql y la manda a la base de datos


        

    return render(request, 'favoritos/crear.html',context)

def borrar_favoritos(request,pk):
    Favoritos.objects.get(pk=pk).delete()

    return redirect('favoritos:lista')
    #return redirect(reverse('favoritos:borrar',kwargs={'pk':pk}))

def detalle_favoritos(request,pk):
    favorito = Favoritos.objects.get(pk=pk)
    return render(request, 'favoritos/detalle.html', context={'object':favorito})

def actualizar_favorito(request,pk):
    favorito = Favoritos.objects.get(pk=pk)
    
    form =FavoritoModelForm(instance=favorito)

    if request.method == 'POST':
        
        form = FavoritoModelForm(request.POST, instance=favorito)

        if form.is_valid():
            form.save()
        else:
            print(form.errrors)
    context = {'form':form , 'titulo' : 'Actualizar'}

    return render(request, 'favoritos/crear.html', context)

favoritos/templates/favoritos/crear.html
{% extends "base_bs5.html" %}

{% block main %}

<div class="container">
    <div class="row">
        <div class="col">

            <h1>{{ titulo }}</h1>

            <form method="post">
            
                    {% csrf_token %}      <!-- Django lo lee y crea un token CSRF desde el backend-->
                    {{ form.as_p }}             <!-- es en "views"/context la llave form// de esta manera accedemos a las variables de contexto en el template-->
                    <input type="submit" class="btn btn-outline-info" onclick="window.alert('Datos enviados')">
            </form>
            
            <a href='{% url 'favoritos:lista' %}' class="btn btn-outline-primary">listas</a>
            
        </div>
    </div>
</div>


    
{% endblock main %}



<!-- <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Crear</title>
</head>
<body>

  
    

     FORMULARIO CAVERNICOLA 
    <form method="post">         <!-- cada vez que se haga una peticion post, hay que mandar un csrf token
        <label>Nombre</label>
        <input type="text" name="nombre">
        <label>url</label>
        <input type="text" name="url">
        <input type="submit">
    </form>
    
</body>
</html>-->

favoritos/templates/favoritos/detalle.html
{% extends "base_bs5.html" %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col">

            <h1>Detalle de {{object.nombre}} {{object.apellido}}</h1>
            <p>contiene la url: <a href='{{object.url}}'> {{object.url}} </a></p>
            <p><a href='{% url 'favoritos:lista' %}' class="btn btn-outline-primary"> lista </a></p>

        </div>
    </div>
</div>

    
{% endblock main %}

favoritos/templates/favoritos/listas.html
{% extends "base_bs5.html" %}

{% block main %}

<h1>{{ titulo }}</h1>

<div class="container">
    <div class="row">
        <div class="col">
            <h1>Lista de favoritos</h1>
            <p>
                <a href="{% url 'favoritos:crear' %}" class="btn btn-outline-primary">Agregar</a>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>
                            nombre
                        </th>
                        <th>
                            apellido
                        </th>
                        <th>
                            URL
                        </th>
        
                    </tr>
                </thead>
                <tbody>
                    <!--Creamos una lista con for, con las lineas de abajo le agregamos "url" a cada elemento-->
                    {% for favorito in favoritos_lista %}   
                    <tr>
                        <td valign="middle">{{ favorito.nombre }}</td>
                        <td valign="middle">{{ favorito.apellido }}</td>
                        <td valign="middle">{{ favorito.url }}</td>
                        <td>
                            <a href="{% url 'favoritos:borrar' favorito.pk %}" class="btn btn-outline-danger mb-2">Borrar</a>
                            <!--<a href="/borrar/{{ favorito.pk }}">Borrar</a> otra forma mas bonita es href="{% url 'favoritos:borrar' favorito.pk%}"-->
                            <br>
                            <a href="{% url 'favoritos:detalle' favorito.pk %}" class="btn btn-outline-info mb-2">Detalle</a>
                            <br>
                            <a href="{% url 'favoritos:actualizar' favorito.pk %}" class="btn btn-outline-primary mb-2">Actualizar</a>
                        </td>
                    </tr>
                    
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<button class="btn btn-outline-info mb-2" onclick="window.print()">Imprimir lista</button>

{% endblock main %}

templates/base_bs5.html
{% load static %} 

<!doctype html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Favoritos</title>
    <link href="{% static 'bs530/css/bootstrap.min.css' %}" rel="stylesheet">

    {% block extra_css %}

    {% endblock %}


  </head>

  <body>
    
    {% block main %}           <!-- CONTENEDOR PRINCIPAL -->
    {% endblock  %} 

    <script src="{% static 'bs530/js/bootstrap.bundle.min.js' %}"></script>

    {% block extra_js %}           <!-- CONTENEDOR PRINCIPAL -->
    {% endblock  %} 

  </body>
</html>

templates/index.html
{% extends "base_bs5.html" %}

{% block main %}



    <h1>Para ingresar un nuevo usuario seleccione "crear"</h1>

    <p><a href='{% url 'favoritos:crear' %}' class="btn btn-outline-primary"> Crear </a></p>



{% endblock main %}